### ISSUE TITLE
Can someone help with public endpoint ?

### ISSUE THREAD

**Issue by akshitv1** [oraichain/cosmosjs#1]
Can i add a publicly available lcdurl so that i can easily interact with mainnet without installing anything. If yes can someone point it out to me? thanks in advance

**Comment by ducphamle2** [comment]
> Can i add a publicly available lcdurl so that i can easily interact with mainnet without installing anything. If yes can someone point it out to me? thanks in advance

We have some open IPs & domains here. You can take a look.

https://github.com/cosmos/chain-registry/blob/master/oraichain/chain.json
